### ISSUE TITLE
Better install instructions

### ISSUE THREAD

**Issue by TheRickRoller** [sizzlemctwizzle/transmission-verify-torrent#4]
As a knob I'm not very sure on how to do a proper install of transmission-verify-torrent,
What I have done is in terminal...
_**cd /Users/TheRickRoller/Downloads/transmission-verify-torrent-master
make && sudo make install**_

After this point I'm lost on what to do or if I have even done the above/install right. Do I need to do anything in transmission or should have I scraped all of the above and just selected the verify-on-completion.sh file (or a different one) in transmission from the downloaded files...please help (:

**Comment by sizzlemctwizzle** [comment]
Check the README again for install instructions. You need to install the compiled application, and then select the completion script in transmission. Anything else you want to do on completion after verification, you add to the bottom of the `verify-on-completion.sh` file. I have transmission use a staging directory for downloads that are complete, but haven't been verified. At the end of the completion script, I move files to the correct final destination. That's about the most basic thing I've done with a completion script.
